#!/bin/bash
#
# NAME="set_pts_off_securetty"
# ARG_NUM="0"
# DESC="set pts off in securetty file"
# 

source modules.d/file_module.sh

function set_pts_off_securetty {
  
	local job_name="$2"
	local job_id="$3"
  local job_id_print=`if [[ ${job_id} -lt 10 ]]; then echo "0${job_id}" ; else echo ${job_id} ; fi`
	local msg_test_success="${job_name} correctly set"
	local msg_test_failure="${job_name} not correctly set"
  local msg_backup_success="${job_name} backup success"
	local msg_backup_failure="${job_name} backup failure"
	local msg_restore_success="${job_name} restore success"
	local msg_restore_failure="${job_name} restore failure"
	local msg_update_success="${job_name} update successfull"
	local msg_update_failure="${job_name} update failed"
	local file_name="/etc/securetty"
	local pattern=""
	local pattern_wanted="pts"
	local keyword="pts"
	local pattern_exist=0
	
	if [[ `file_exist "file" "${file_name}"` -eq 1 ]]; then
	
		res=`file_match_pattern "${file_name}" "${pattern_wanted}" "${keyword}"`
		pattern_exist=`echo "${res}" | awk -F\| '{print $1}'`
	
		if [[ ${pattern_exist} -eq 0 ]]; then
	
			pattern=`echo "${res}" | awk -F\| '{print $2}'`
	
		fi
		
	else
	
		prt_func_res ${job_id_print} ${job_name} "TEST" "WARNING" "the file ${file_name} not found"
		
	fi

	case $1 in
		test)

			if [[ ${pattern_exist} -eq 0 ]]; then

				prt_func_res ${job_id_print} ${job_name} "TEST" "OK" "${msg_test_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "TEST" "NOK" "${msg_test_failure}"

			fi
		;;
		
		backup)

			cmd_str=""
			for secure_pattern in `egrep "^pts\/[0-9]*$" "${file_name}"`; do

				cmd_str=${cmd_str}"${secure_pattern}\n"

			done
			cmd_line="echo -e \"${cmd_str}\" >> \"${file_name}\""

			if [[ `metadata_write_restore_cmd "${job_id}" "${cmd_line}"` -eq 1 ]]; then

				prt_func_res ${job_id_print} ${job_name} "BACKUP" "OK" "${msg_backup_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "BACKUP" "NOK" "${msg_backup_failure}"
	
			fi
		;;

		update)

			sed -i "/^pts/d" "${file_name}" &>/dev/null
	
			if [[ $? -eq 0 ]]; then

				prt_func_res ${job_id_print} ${job_name} "UPDATE" "OK" "${msg_update_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "UPDATE" "NOK" "${msg_update_failure}"

			fi
		;;

		restore)

			if [[ `metadata_is_restore_cmd "${job_id}"` -eq 1 ]]; then
			
				local restore_cmd=`metadata_get_restore_cmd "${job_id}"`
				eval ${restore_cmd}

				prt_func_res ${job_id_print} ${job_name} "RESTORE" "OK" "${msg_restore_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "RESTORE" "NOK" "${msg_restore_failure}"

			fi		
		;;

		esac
}
