#!/bin/bash
#
# NAME="set_init_runlevel_3"
# ARG_NUM="0"
# DESC="set default init runlevel to 3 for redhat 6"
# 

source modules.d/file_module.sh

function set_init_runlevel_3 {

	local job_name="$2"
	local job_id="$3"
  local job_id_print=`if [[ ${job_id} -lt 10 ]]; then echo "0${job_id}" ; else echo ${job_id} ; fi`
	local msg_test_success="default init level 3 correctly set"
	local msg_test_failure="default init level 3 not correctly set"
  local msg_backup_success="default init backup success"
	local msg_backup_failure="default init backup failed"
	local msg_restore_success="restore default init level 3 success"
	local msg_restore_failure="restore default init level 3 failed"
	local msg_update_success="update default init level 3 success"
	local msg_update_failure="update default init level 3 failed"
	local run_level=3
	local init_file="/etc/inittab"
	local init_run_level=`awk -F\: '/^id/ {print $2}' "${init_file}"`

	case $1 in
		test)
		
			if [[ ${init_run_level} -eq 3 ]]; then

				prt_func_res ${job_id_print} ${job_name} "TEST" "OK" "${msg_test_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "TEST" "NOK" "${msg_test_failure}"

			fi
		;;

		update)
			
			sed -i "s/id\:[1-6]\:initdefault\:/id\:3\:initdefault\:/" "${init_file}" &>/dev/null

			if [[ $? -eq 0 ]]; then

				prt_func_res ${job_id_print} ${job_name} "UPDATE" "OK" "${msg_update_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "UPDATE" "NOK" "${msg_update_failure}"
		
			fi
		;;

		backup)

			if [[ `update_metadata "${job_id}" "file" ${init_file}` -eq 1 ]]; then

				prt_func_res ${job_id_print} ${job_name} "BACKUP" "OK" "${msg_backup_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "BACKUP" "NOK" "${msg_backup_failure}"

			fi
		;;

		restore)

			if [[ `grep "^cmd\[${job_id}\]=" ${global_restore_metadata} | wc -l` -eq 1 ]]; then
			
				local restore_cmd=`grep "^cmd\[${job_id}\]=" ${global_restore_metadata}| awk -F]= '{print $2}'`
				eval ${restore_cmd}

				prt_func_res ${job_id_print} ${job_name} "RESTORE" "OK" "${msg_restore_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "RESTORE" "NOK" "${msg_restore_failure}"

			fi		
		;;

	esac
}