#!/bin/bash
#
# NAME="update_umask_bashrc"
# ARG_NUM="0"
# DESC="this is a strict mode add line into file. the line arg will be surrounded by ^$"
#

function update_umask_bashrc {

	local job_name="$2"
	local job_id="$3"
	local job_id_print=`if [[ ${job_id} -lt 10 ]]; then echo "0${job_id}" ; else echo ${job_id}; fi`
	local msg_test_success="${job_name} correctly set"
	local msg_test_failure="${job_name} not correctly set"
  local msg_backup_success="${job_name} backup success"
	local msg_backup_failure="${job_name} backup failed"
	local msg_restore_success="${job_name} restore success"
	local msg_restore_failure="${job_name} restore failed"
	local msg_update_success="${job_name} update success"
	local msg_update_failure="${job_name} update failed"
	local file_name="/etc/bashrc"
	local pattern_exist=0
	
	if [[ `sed -n '/umask\ 0027/p' ${file_name} | wc -l` -gt  0 ]]; then

		pattern_exist=1

	fi

	case $1 in
		test)
		
			if [[ ${pattern_exist} -eq 1 ]]; then

				prt_func_res ${job_id_print} ${job_name} "TEST" "OK" "${msg_test_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "TEST" "NOK" "${msg_test_failure}"

			fi
			;;

		backup)

			cmd_line="sed -i '/umask\ 0027/d' ${file_name} 2>/dev/null >/dev/null ; umask 0022 ;"
			if [[ `metadata_write_restore_cmd "${job_id}" "${cmd_line}"` -eq 1 ]]; then

				prt_func_res ${job_id_print} ${job_name} "BACKUP" "OK" "${msg_backup_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "BACKUP" "NOK" "${msg_backup_failure}"

			fi
		;;

		restore)

			if [[ `metadata_is_restore_cmd "${job_id}"` -eq 1 ]]; then
			
				local restore_cmd=`metadata_get_restore_cmd "${job_id}"`
				eval ${restore_cmd}

				prt_func_res ${job_id_print} ${job_name} "RESTORE" "OK" "${msg_restore_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "RESTORE" "NOK" "${msg_restore_failure}"
			
			fi		
		;;

		update)
				
			echo "if [[ \`id -u\` -eq 0 ]]; then umask 0027 ; fi" 2>/dev/null >> "${file_name}" && umask 0027

			if [[ $? -eq 0 ]]; then

				prt_func_res ${job_id_print} ${job_name} "UPDATE" "OK" "${msg_update_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "UPDATE" "NOK" "${msg_update_failure}"

			fi 
		;;

		*)
			exit 1
		;;

		esac
}