#!/bin/bash
#
# NAME="create_dir"
# ARG_NUM="1"
# ARG#1="directory name you would like to create"
# DESC="create directory"
#

source modules.d/file_module.sh

function create_dir {
	
	local job_name="$2"
  local job_id="$3"
  local file_name="$4"
	local job_id_print=`if [[ ${job_id} -lt 10 ]]; then echo "0${job_id}" ; else echo ${job_id} ; fi`
	local msg_test_success="${file_name} exists in system tree"
	local msg_test_failure="${file_name} missing in system tree"
  local msg_backup_success="backup ${file_name} successfull"
	local msg_backup_failure="backup ${file_name} failed"
	local msg_restore_success="restore ${file_name} successfull"
	local msg_restore_failure="restore ${file_name} failed"
	local msg_update_success="add ${file_name} successfull to system tree"
	local msg_update_failure="add ${file_name} failed to system tree"

	case $1 in
		test)

			if [[ `file_exist "dir" "${file_name}"` -eq 1  ]]; then
				
				prt_func_res ${job_id_print} ${job_name} "TEST" "OK" "${msg_test_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "TEST" "NOK" "${msg_test_failure}"

			fi
		;;

		backup)

			cmd_line="rm -fr ${file_name} &>/dev/null"
			if [[ `metadata_write_restore_cmd "${job_id}" "${cmd_line}"` -eq 1 ]]; then

				prt_func_res ${job_id_print} ${job_name} "BACKUP" "OK" "${msg_backup_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "BACKUP" "NOK" "${msg_backup_failure}"

			fi			
		;;

		restore)

			if [[ `metadata_is_restore_cmd "${job_id}"` -eq 1 ]]; then
			
				local restore_cmd=`metadata_get_restore_cmd "${job_id}"`
				eval ${restore_cmd}

				prt_func_res ${job_id_print} ${job_name} "RESTORE" "OK" "${msg_restore_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "RESTORE" "NOK" "${msg_restore_failure}"

			fi		
		;;

		update)

			if [[ `file_create "dir" ${file_name}` -eq 1 ]]; then

				prt_func_res ${job_id_print} ${job_name} "UPDATE" "OK" "${msg_update_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "UPDATE" "NOK" "${msg_update_failure}"

			fi
		;;

		*)
		;;

	esac

}
