#!/bin/bash
#
# NAME="delete_group"
# ARG_NUM="1"
# DESC="delete group"

source modules.d/group_module.sh

function delete_group {

	local job_name="$2"
	local job_id="$3"
  local group_name="$4"
	local job_id_print=`if [[ ${job_id} -lt 10 ]]; then echo "0${job_id}" ; else echo ${job_id} ; fi`
	local msg_test_success="group $group_name correctly set"
	local msg_test_failure="group $group_name not correctly set"
  local msg_backup_success="backup group $group_name success"
	local msg_backup_failure="backup group $group_name failed"
	local msg_restore_success="restore group $group_name success"
	local msg_restore_failure="restore group $group_name failed"
	local msg_update_success="update group $group_name success"
	local msg_update_failure="update group $group_name failed"
	local group_exist=0
	
	if [[ `group_exist "${group_name}"` -eq  1 ]]; then

		group_exist=1

	fi

	case $1 in
		test)
		
			if [[ ${group_exist} -eq 0 ]]; then

				prt_func_res ${job_id_print} ${job_name} "TEST" "OK" "${msg_test_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "TEST" "NOK" "${msg_test_failure}"

			fi
		;;

		backup)

			cmd_line=`group_restore_cmd_get ${group_name}`

			if [[ `metadata_write_restore_cmd "${job_id}" "${cmd_line}"` -eq 1 ]]; then

				prt_func_res ${job_id_print} ${job_name} "BACKUP" "OK" "${msg_backup_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "BACKUP" "NOK" "${msg_backup_failure}"

			fi
		;;

		restore)

			if [[ `metadata_is_restore_cmd "${job_id}"` -eq 1 ]]; then
			
				local restore_cmd=`metadata_get_restore_cmd "${job_id}"`
				eval ${restore_cmd}

				prt_func_res ${job_id_print} ${job_name} "RESTORE" "OK" "${msg_restore_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "RESTORE" "NOK" "${msg_restore_failure}"
			
			fi		
		;;

		update)

			if [[ `group_delete "${group_name}"` -eq 1 ]]; then

				prt_func_res ${job_id_print} ${job_name} "UPDATE" "OK" "${msg_update_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "UPDATE" "NOK" "${msg_update_failure}"

			fi 
		;;

		*)
			exit 1
		;;

		esac
}

