#!/bin/bash
#
# NAME="set_auth_passwd_history"
# ARG_NUM="0"
# DESC="set auth password history"
# 

source modules.d/file_module.sh

function set_auth_passwd_history {

	local job_name="$2"
	local job_id="$3"
  local job_id_print=`if [[ ${job_id} -lt 10 ]]; then echo "0${job_id}" ;  else echo ${job_id} ; fi`
	local msg_test_success="${job_name} correctly set"
	local msg_test_failure="${job_name} not correctly set"
  local msg_backup_success="${job_name} backup success"
	local msg_backup_failure="${job_name} backup failed"
	local msg_restore_success="${job_name} restore success"
	local msg_restore_failure="${job_name} restore failed"
	local msg_update_success="${job_name} update success"
	local msg_update_failure="${job_name} update failed"
	local file_name="/etc/pam.d/system-auth"
	local pattern_exist=0
	local string="remember=10"

	if [[ `egrep -oc "password.*pam_unix\.so.*${string}" ${file_name} 2>/dev/null` -eq 0 ]]; then

		local pattern_exist=1

	else

		local pattern=`egrep "password.*pam_unix\.so" ${file_name} | egrep -o "remember=[1-9]*"`

	fi


	case $1 in
		test)

			if [[ ${pattern_exist} -eq 0 ]]; then

				prt_func_res ${job_id_print} ${job_name} "TEST" "OK" "${msg_test_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "TEST" "NOK" "${msg_test_failure}"

			fi
		;;

		backup)

			cmd_line="sed -i 's/remember=10\ /${pattern}/' ${file_name} &>/dev/null" 

			if [[ `metadata_write_restore_cmd "${job_id}" "${cmd_line}"` -eq 1 ]]; then

				prt_func_res ${job_id_print} ${job_name} "BACKUP" "OK" "${msg_backup_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "BACKUP" "NOK" "${msg_backup_failure}"

			fi
		;;

		update)

			egrep "password.*pam_unix\.so.*remember=" ${file_name} &>/dev/null
				
			if [[ $? -eq 0 ]]; then

				sed -i "s/remember=[1-9]*/remember=10/" "${file_name}" &>/dev/null

			else

				str_to_replace=`egrep "password.*pam_unix\.so" ${file_name} | awk '{print $4}'`
				sed -i "s/${str_to_replace}/${str_to_replace} remember=10/" "${file_name}" &>/dev/null

			fi

			if [[ $? -eq 0 ]]; then

				prt_func_res ${job_id_print} ${job_name} "UPDATE" "OK" "${msg_update_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "UPDATE" "NOK" "${msg_update_failure}"
		
			fi
		;;

		restore)

			if [[ `metadata_is_restore_cmd "${job_id}"` -eq 1 ]]; then
			
				local restore_cmd=`metadata_get_restore_cmd "${job_id}"`
				eval ${restore_cmd}

				prt_func_res ${job_id_print} ${job_name} "RESTORE" "OK" "${msg_restore_success}"

			else
				
				prt_func_res ${job_id_print} ${job_name} "RESTORE" "NOK" "${msg_restore_failure}"

			fi		
		;;

	esac
}